---
- name: UnInstall Windows-Defender
  win_feature:
    name: Windows-Defender
    state: absent

- name: UnInstall XPS-Viewer
  win_feature:
    name: XPS-Viewer
    state: absent

# The win_package menu does not support AppX packages yet so we need to run PowerShell commands
- name: Uninstall {{ package }}
  win_command:
    cmd: Get-AppxPackage -AllUsers -Name *{{ package }}* | Remove-AppxPackage -AllUsers
  loop:
    - WindowsMaps
    - WindowsSoundRecorder
    - WindowsCamera
    - WindowsAlarms
    - WindowsFeedbackHub
    - windowscommunicationsapps
    - WindowsPhone
    - BingNews
    - BingFinance
    - BingSports
    - BingWeather
    - ZuneVideo
    - ZuneMusic
    - SkypeApp
    - MicrosoftOfficeHub
    - Messaging
    - Advertising.Xaml
    - Office.OneNote
    - OneConnect
    - Getstarted
    - Phone
    - Sway
    - Print3D
    - Microsoft3DViewer
    - 3DBuilder
    - NetworkSpeedTest
    - RemoteDesktop
    - Wallet
    - BubbleWitch
    - HiddenCity
    - Disney
    - MarchofEmpires
    - CandyCrush
    - MicrosoftSolitaireCollection
    - RoyalRev
    - COOKINGFEVER
    - PowerBI
    - Eclipse
    - AdobePhotoshopExpress
    - Sling
    - Duolingo
    - PhototasticCollage
    - Keeper
    - SketchBook
    - DolbyAccess
    - Fitbit
    - Spotify
    - Pandora
    - twitter
    - Facebook
    - XboxApp
  loop_control:
    loop_var: package
